name: accenture-song
recipe: drupal9
config:
  php: '7.4'
  composer_version: '2.1.14'
  via: apache
  webroot: web
  database: mysql:5.7
  drush: false
  xdebug: false
services:
  appserver:
    scanner: false
    build:
      - composer install
  database:
    type: mysql:5.7
    portforward: true
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      environment:
        PMA_HOST: database
        PMA_USER: root
